ai_lab:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: "{{env_var('WEBSHOP_POSTGRES_USER')}}"
      password: "{{env_var('WEBSHOP_POSTGRES_PASSWORD')}}"
      port: 5432
      dbname: webshop_v2
      schema: webshop
      threads: 6
